#!/usr/bin/python
#
# Example client showing use of command_hook_mirror
#
# Example config:
# |stream_load: 'cat $XFILE 2>/dev/null || :'
# |item_insert: [sh, -c, "echo %(serial)s >> $XFILE; echo inserted %(serial)s"]
# |group_insert_pre: [bash, -c, "echo --; for f in ${_fields}; do echo $f: ${!f}; done"]
# |unset_value: _unset
# |item_skip_download: true
#

from simplestreams import collection
from simplestreams import command_hook_mirror
from simplestreams import objectstores
from simplestreams import stream
from simplestreams import util
import toolutil

import sys
import os


def main():
    cfg_file = sys.argv[1]
    urls = sys.argv[2:]

    with open(cfg_file) as cfp:
        cfg_content = cfp.read()

    cfg = util.load_content(cfg_content)

    for url in urls:
        tmirror = command_hook_mirror.CommandHookMirror(cfg)

        resolve_args = {'max': cfg.get("max"), 'keep': cfg.get("keep")}

        norm_url = toolutil.normalize_url(url)
        (src_url, path) = toolutil.tokenize_url(norm_url)
        print "path=%s src_url=%s" % (path, src_url)
        smirror = objectstores.UrlMirrorReader(src_url)

        (content, _sig) = util.read_possibly_signed(path,
                                                    smirror.reader)

        data = util.load_content(content)
        fmt = data.get("format")

        if fmt == "stream-1.0":
            print "%s (%s)" % (path, fmt)
            sstream = stream.Stream(data)
            util.sync_stream(src_stream=sstream,
                             src_mirror=smirror, target_stream=None,
                             target_mirror=tmirror, path=path,
                             resolve_args=resolve_args)

        elif fmt == "stream-collection:1.0":
            scoll = collection.Collection(data)
            print "%s (%s) [%s]" % (path, fmt, scoll.iqn)
            util.sync_collection(src_collection=scoll, src_mirror=smirror,
                                 target_mirror=tmirror, path=path,
                                 resolve_args=resolve_args)

        else:
            print "Unknown format '%s' in '%s'" % (fmt, url)
            sys.exit(1)

if __name__ == '__main__':
    main()
