#!/bin/bash

TOP_DIR=$(cd "$(dirname "${0}")"/.. && pwd)
GPG_DIR=${TOP_DIR}/gnupg
TENV=${TOP_DIR}/tools/tenv
PUBKEY=${TOP_DIR}/examples/keys/example.pub
SECKEY=${TOP_DIR}/examples/keys/example.sec

if [ -f "$GPG_DIR"/README ]
then
    echo "Files exist, not regenerating." 
    exit
fi

echo -e "\nSetting up GPG keys..."
umask 077 && mkdir -p "$GPG_DIR"

if [ ! -f "$PUBKEY" -o ! -f "$SECKEY" ]
then
    mkdir -p "$(dirname "$PUBKEY")"
    out=$($TENV "${TOP_DIR}"/tools/gen-example-key "$PUBKEY" "$SECKEY") ||
        { echo "Failed to generate keys: $out"; exit 2; }
fi

out=$($TENV gpg --import "$SECKEY" >/dev/null 2>&1 ) ||
    { echo "Failed to import seckey: $out"; exit 2; }
out=$("${TOP_DIR}"/tools/gpg-trust-pubkey "$PUBKEY") ||
    { echo "Failed to import pubkey: $out"; exit 2; }

echo "this is used by $TENV as the gpg directory" > "$GPG_DIR"/README

