#!/usr/bin/python3

import os
import os.path
import json
import sys

import toolutil


def status_cb(fname):
    sys.stderr.write("%s\n" % fname)

def main():
    for path in sys.argv[1:]:
        if os.path.isfile(path):
            if not path.endswith(".json"):
                sys.stderr.write("file must end with .json\n")
                sys.exit(1)
            toolutil.signjson_file(path)
        elif os.path.isdir(path):
            for root, dirs, files in os.walk(path):
                for f in [f for f in files if f.endswith(".json")]:
                    toolutil.signjson_file(os.path.join(root, f), status_cb=status_cb)
        else:
            sys.stderr.write("input must be file or dir\n")
            sys.exit(1)


if __name__ == '__main__':
    import sys
    main()
