#!/bin/bash

if [ $# -eq 0 ]; then
   files=( $(find * -name "*.py" -type f)
           $(for f in bin/*; do [ "${f%.*}" = "$f" ] && echo "$f"; done) )
else
   files=( "$@" );
fi

PYTHON_VERSION=${PYTHON_VERSION:-3}

if [ "$PYTHON_VERSION" = "2" ]; then
    pyflakes="pyflakes"
else
    pyflakes="pyflakes3"
fi

cmd=( $pyflakes "${files[@]}" )

echo -e "\nRunning pylint:"
echo "${cmd[@]}"
"${cmd[@]}"
