#!/bin/bash

if [ $# -eq 0 ]; then
   files=( $(find * -name "*.py" -type f)
           $(for f in bin/*; do [ "${f%.*}" = "$f" ] && echo "$f"; done) 
           tools/make-test-data
         )
else
   files=( "$@" );
fi

cmd=( flake8 "${files[@]}" )

echo -e "\nRunning flake8:"
echo "${cmd[@]}"
"${cmd[@]}"
