#!/bin/sh
error() { echo "$@" 1>&2; }
mydir=${0%/*}
myname=sstream-mirror-glance
bindir=$(cd "$mydir/../bin" && pwd) && [ -x "$bindir/$myname" ] || {
    error "Failed to find simplestreams bin/$myname based on '$mydir/../bin'"
    error "please call simplestreams/tools/$myname from bin/$myname now."
    exit 1
}
error "WARNING: simplestreams tools/$myname has moved to bin/$myname."
error "WARNING: Please update any scripts using it from the old path."
exec "$bindir/$myname" "$@"
